version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - eliasnorrby
  versioning-strategy: widen
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@eliasnorrby/prettier-config"
    versions:
    - 4.2.19
    - 4.2.23
    - 4.2.24
    - 4.2.25
    - 4.2.26
    - 4.2.27
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@eliasnorrby/log-util"
    versions:
    - 1.1.8
    - 1.1.9
  - dependency-name: semantic-release
    versions:
    - 17.3.7
    - 17.3.8
    - 17.3.9
    - 17.4.0
    - 17.4.1
  - dependency-name: "@types/yargs"
    versions:
    - 15.0.12
    - 16.0.0
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
